codeon/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

from codeon.views import registration, home

admin.autodiscover()


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name='home'),

    url(r'^registration/$', registration, name='registration'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {
            'template_name': 'login.html',
            'redirect_field_name': settings.LOGIN_REDIRECT_URL,
        }, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.LOGOUT_URL}, name="logout"),

    url(r'^groups/', include('student.urls', namespace='student')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.conf.urls import patterns, url

from student.views import StudentGroupList, StudentGroupDelete, StudentGroupAdd, StudentGroupUpdate, StudentsOfGroup, \
    StudentUpdate, StudentCreate, StudentDelete


urlpatterns = patterns('',
    url(r'^all/$', StudentGroupList.as_view(), name='group_list'),
    url(r'^delete/(?P<pk>[\d]+)/$', StudentGroupDelete.as_view(), name='group_delete'),
    url(r'^add/$', StudentGroupAdd.as_view(), name='group_add'),
    url(r'^update/(?P<pk>[\d]+)/$', StudentGroupUpdate.as_view(), name='group_update'),
    url(r'^students/(?P<group_id>[\d]+)/$', StudentsOfGroup.as_view(), name='students_of_group'),

    url(r'^students/update/(?P<pk>[\d]+)/$', StudentUpdate.as_view(), name='student_update'),
    url(r'^students/add/$', StudentCreate.as_view(), name='student_add'),
    url(r'^students/delete/(?P<pk>[\d]+)/$', StudentDelete.as_view(), name='student_delete'),
)

student/models.py
import os
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _

OPERATION_CHOICES = (
    (0, 'CREATION'),
    (1, 'EDITING'),
    (2, 'REMOVAL'),
)


class StudentGroup(models.Model):
    name = models.CharField(max_length=30, verbose_name=_('Name'))
    headman = models.OneToOneField('student.Student', null=True, blank=True,
        verbose_name=_('Headman'), on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.name

    def clean(self):
        if self.headman and self.headman.group.pk != self.pk:
                raise ValidationError(_('Student must be a member of group.'))


class Student(models.Model):
    first_name = models.CharField(max_length=30, verbose_name=_('First name'))
    last_name = models.CharField(max_length=30, verbose_name=_('Last name'))
    middle_name = models.CharField(max_length=30, verbose_name=_('Middle name'))
    photo = models.ImageField(upload_to='students_photo', verbose_name=_('Photo'))
    birthday = models.DateField(verbose_name=_('Birthday'))
    ticket = models.CharField(max_length=6, unique=True, verbose_name=_('Ticket number'))
    group = models.ForeignKey(StudentGroup, related_name='students_of_group', verbose_name=_('Group'))

    def __unicode__(self):
        return self.ticket


# Drop image before delete Student object
def drop_image(sender, instance, **kwargs):
    try:
        if instance.photo and os.path.isfile(instance.photo.path):
            os.remove(instance.photo.path)
    except Exception, error:
        print error


class ModelsChanges(models.Model):
    model_name = models.CharField(max_length=100, verbose_name=_('Model name'))
    obj_id = models.IntegerField(verbose_name='Object ID')
    operation = models.IntegerField(choices=OPERATION_CHOICES, default=0)
    operation_date = models.DateTimeField(auto_now=True)


def log_model_changes(sender, instance, **kwargs):
    '''
    Connect post_save and post_dalete signals for logging operations
    '''
    default_operation = 0
    if 'created' in kwargs.keys():
        if not kwargs['created']:
            default_operation = 1
    else:
        default_operation = 2
    ModelsChanges.objects.create(model_name=instance._meta.db_table, obj_id=instance.id, operation=default_operation)


models.signals.post_delete.connect(drop_image, sender=Student)
models.signals.post_save.connect(log_model_changes, sender=Student)
models.signals.post_delete.connect(log_model_changes, sender=Student)

student/views.py
from django.core.urlresolvers import reverse_lazy
from django.http.response import HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Count

from student.models import StudentGroup, Student


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)


# Groups
class StudentGroupList(LoginRequiredMixin, ListView):
    # model = StudentGroup
    queryset = StudentGroup.objects.all().select_related("headman").annotate(students_count=Count("students_of_group"))
    template_name = 'student/groups_show.html'


class StudentGroupDelete(LoginRequiredMixin, DeleteView):
    model = StudentGroup
    template_name = 'student/group_delete.html'
    success_url = reverse_lazy('student:group_list')


class StudentGroupAdd(LoginRequiredMixin, CreateView):
    model = StudentGroup
    template_name = 'student/group_add.html'
    fields = ['name']
    success_url = reverse_lazy('student:group_list')


class StudentGroupUpdate(LoginRequiredMixin, UpdateView):
    model = StudentGroup
    template_name = 'student/group_update.html'
    fields = ['name', 'headman']
    success_url = reverse_lazy('student:group_list')

    def get_context_data(self, **kwargs):
        context = super(StudentGroupUpdate, self).get_context_data(**kwargs)
        context['form'].fields['headman'].queryset = self.object.students_of_group.all()
        return context


class StudentsOfGroup(LoginRequiredMixin, ListView):
    model = Student
    template_name = 'student/group_members.html'

    def get_queryset(self):
        self.group = get_object_or_404(StudentGroup, id=self.kwargs['group_id'])
        return self.group.students_of_group.all()

    def get_context_data(self, **kwargs):
        context = super(StudentsOfGroup, self).get_context_data(**kwargs)
        context['group'] = self.group
        context['headman'] = self.group.headman
        return context


# Students
class StudentDelete(LoginRequiredMixin, DeleteView):
    model = Student
    template_name = 'student/student_delete.html'
    success_url = reverse_lazy('student:group_list')


class StudentUpdate(LoginRequiredMixin, UpdateView):
    model = Student
    template_name = 'student/student_update.html'
    fields = ['first_name', 'last_name', 'middle_name', 'photo', 'birthday', 'ticket', 'group']

    def form_valid(self, form):
        self.object = form.save()

        # What if we change headman of group?
        if self.object.group.pk != form.initial['group']:
            try:
                group = StudentGroup.objects.get(id=form.initial['group'])
                if group.headman == self.object:
                    group.headman = None
                    group.save()
            except StudentGroup.DoesNotExist, error:
                print error
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('student:students_of_group', kwargs={'group_id': self.object.group.pk})


class StudentCreate(LoginRequiredMixin, CreateView):
    model = Student
    template_name = 'student/student_add.html'
    fields = ['first_name', 'last_name', 'middle_name', 'photo', 'birthday', 'ticket', 'group']

    def get_success_url(self):
        return reverse_lazy('student:students_of_group', kwargs={'group_id': self.object.group.pk})

templates/student/group_add.html
{% extends 'navigation.html' %}
{% load i18n %}
{% load bootstrap %}

{% block pagescript%}
{% endblock %}

{% block pagestyle%}
{% endblock %}

{% block content %}
    <div class="col-md-10 col-md-offset-1">
        <h1 class="text-center">Group create</h1>
        <form method="post">{% csrf_token %}
            {{ form|bootstrap }}
            <div class="text-center">
                <input type="submit" class="btn btn-primary" value="{% trans "Create" %}">
            </div>
        </form>
    </div>
{% endblock %}

templates/student/group_delete.html
{% extends 'navigation.html'%}
{% load i18n %}

{% block pagescript%}
{% endblock %}

{% block pagestyle%}
{% endblock %}

{% block content %}
    <div class="col-md-10 col-md-offset-1">
        <form  method="post">{% csrf_token %}
            <div class="text-center">
                <p>{% trans "Are you sure you want to delete group " %} "{{ object }}"?</p>
                <input type="submit" class="btn btn-primary" value="{% trans "Confirm" %}">
            </div>
        </form>
    </div>
{% endblock %}

templates/student/group_members.html
{% extends 'navigation.html'%}
{% load i18n %}
{% load thumbnail %}
{% load pagination_tags %}
{% load code_on %}

{% block pagescript%}
{% endblock %}

{% block pagestyle%}
    <style>
        #group-members tbody>tr>td{
            vertical-align: middle;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="col-md-10 col-md-offset-1">
        <div class="text-center">
            <h1>Students of the group "{{ group.name }}"</h1>
        </div>
        <div>
            <table id="group-members" class="table table-striped table-hover">
                <tr>
                    <th>{% trans 'Photo' %}</th>
                    <th>{% trans 'Student name' %}</th>
                    <th>{% trans 'Ticket number' %}</th>
                    <th>{% trans 'Birthday' %}</th>
                    <th>{% trans 'Actions' %}</th>
                    <th>{% trans 'Edit like admin' %}</th>
                </tr>
                {% autopaginate object_list %}
                {% for student in object_list %}
                    <tr class="{% if student.pk == headman.pk %}success{% endif %}">
                        <td>
                            {% thumbnail student.photo "100x100" crop="center" as im %}
                                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                            {% endthumbnail %}
                        </td>
                        <td>
                            {{ student.last_name }}
                            {{ student.first_name }}
                            {{ student.middle_name }}
                        </td>
                        <td>
                            {{ student.ticket }}
                        </td>
                        <td>
                            {{ student.birthday|date:"d F Y"  }}
                        </td>
                        <td>
                            <a href="{% url 'student:student_update' student.pk %}" class="btn btn-success btn-sm">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                            <a href="{% url 'student:student_delete' student.pk %}" class="btn btn-danger btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        </td>
                    <td class="text-center">
                        <a href="{% edit_url student %}" class="btn btn-success btn-sm">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6">
                            <div class="text-center">{% trans 'No students yet.' %}</div>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="text-center">
            {% paginate %}
        </div>
    </div>

{% endblock %}

templates/student/group_update.html
{% extends 'navigation.html' %}
{% load i18n %}
{% load bootstrap %}

{% block pagescript%}
{% endblock %}

{% block pagestyle%}
{% endblock %}

{% block content %}
    <div class="col-md-10 col-md-offset-1">
        <h1 class="text-center">Group change</h1>
        <form action="" method="post">{% csrf_token %}
            {{ form|bootstrap }}
            <div class="text-center">
                <input type="submit" class="btn btn-primary" value="{% trans "Change" %}">
            </div>
        </form>
    </div>
{% endblock %}

templates/student/groups_show.html
{% extends 'navigation.html' %}
{% load i18n %}
{% load code_on %}

{% block pagescript%}
{% endblock %}

{% block pagestyle%}
{% endblock %}

{% block content %}
    <div class="col-md-10 col-md-offset-1">
        <div class="text-center">
            <h1>Student groups</h1>
        </div>

        <div>
            <table id="group-table" class="table table-bordered">
                <tr>
                    <th class="text-center">{% trans 'Name' %}</th>
                    <th class="text-center">{% trans 'Students count' %}</th>
                    <th class="text-center">{% trans 'Headman' %}</th>
                    <th class="text-center">{% trans 'Actions' %}</th>
                    <th class="text-center">{% trans 'Edit like admin' %}</th>
                </tr>
                {% for group in object_list %}
                    <tr>
                        <td class="text-center">
                            {% if group.students_count != 0 %}
                                <a href="{% url 'student:students_of_group' group.pk %}">
                                    {{ group.name }}
                                </a>
                            {% else %}
                                {{ group.name }}
                            {% endif %}
                        </td>
                        <td class="text-center">{{ group.students_count }}</td>
                        <td class="text-center">
                            {% if group.headman %}
                                {{ group.headman }}</td>
                            {% else %}
                                ------
                            {% endif %}
                        <td class="text-center">
                            <a href="{% url 'student:group_update' group.pk %}" class="btn btn-success btn-sm">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                            <a href="{% url 'student:group_delete' group.pk %}" class="btn btn-danger btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="{% edit_url group %}" class="btn btn-success btn-sm">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5">
                            <div class="text-center">{% trans 'No groups yet.' %}</div>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>

        <div class="text-center">
            {% if object_list.count != 0 %}
                <a href="{% url 'student:student_add'%}" class="btn btn-success btn-sm">
                    <span class="glyphicon glyphicon-plus"></span> {% trans "Add student" %}
                </a>
            {% endif %}
            <a href="{% url 'student:group_add' %}" class="btn btn-primary btn-sm">
                <span class="glyphicon glyphicon-plus"></span> {% trans "Add group" %}
            </a>
        </div>
    </div>
{% endblock %}

templates/student/student_add.html
{% extends 'navigation.html' %}
{% load i18n %}
{% load bootstrap %}

{% block pagescript%}
    <script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script>
        $(document).ready(function(){
            $( "#id_birthday" ).datepicker({
                dateFormat: '{{ settings.JS_DATE_FORMAT }}',
                changeMonth: true,
                changeYear: true
            }).prop('readonly', true);
        });
    </script>
{% endblock %}

{% block pagestyle%}
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
{% endblock %}

{% block content %}
    <div class="col-md-10 col-md-offset-1">
        <h1 class="text-center">Student create</h1>
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form|bootstrap }}
            <div class="text-center">
                <input type="submit" class="btn btn-primary" value="{% trans "Create" %}">
            </div>
        </form>
    </div>
{% endblock %}

templates/student/student_delete.html
{% extends 'navigation.html'%}
{% load i18n %}

{% block pagescript%}
{% endblock %}

{% block pagestyle%}
{% endblock %}

{% block content %}
    <div class="col-md-10 col-md-offset-1">
        <form action="" method="post">{% csrf_token %}
            <div class="text-center">
                <p>{% trans "Are you sure you want to delete student " %} "{{ object }}"?</p>
                <input type="submit" class="btn btn-primary" value="{% trans "Confirm" %}">
            </div>
        </form>
    </div>
{% endblock %}

templates/student/student_update.html
{% extends 'navigation.html' %}
{% load i18n %}
{% load bootstrap %}

{% block pagescript%}
    <script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script>
        $(document).ready(function(){
            $( "#id_birthday" ).datepicker({
                dateFormat: '{{ settings.JS_DATE_FORMAT }}',
                changeMonth: true,
                changeYear: true
            }).prop('readonly', true);
        });
    </script>
{% endblock %}

{% block pagestyle%}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
{% endblock %}

{% block content %}
    <div class="col-md-10 col-md-offset-1">
        <h1 class="text-center">Student change</h1>
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form|bootstrap }}
            <div class="text-center">
                <input type="submit" class="btn btn-primary" value="{% trans "Change" %}">
            </div>
        </form>
    </div>
{% endblock %}