codeon/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

from codeon.views import registration, home

admin.autodiscover()


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name='home'),

    url(r'^registration/$', registration, name='registration'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {
            'template_name': 'login.html',
            'redirect_field_name': settings.LOGIN_REDIRECT_URL,
        }, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.LOGOUT_URL}, name="logout"),

    url(r'^groups/', include('student.urls', namespace='student')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.conf.urls import patterns, url

from student.views import StudentGroupList, StudentGroupDelete, StudentGroupAdd, StudentGroupUpdate, StudentsOfGroup, \
    StudentUpdate, StudentCreate, StudentDelete


urlpatterns = patterns('',
    url(r'^all/$', StudentGroupList.as_view(), name='group_list'),
    url(r'^delete/(?P<pk>[\d]+)/$', StudentGroupDelete.as_view(), name='group_delete'),
    url(r'^add/$', StudentGroupAdd.as_view(), name='group_add'),
    url(r'^update/(?P<pk>[\d]+)/$', StudentGroupUpdate.as_view(), name='group_update'),
    url(r'^students/(?P<group_id>[\d]+)/$', StudentsOfGroup.as_view(), name='students_of_group'),

    url(r'^students/update/(?P<pk>[\d]+)/$', StudentUpdate.as_view(), name='student_update'),
    url(r'^students/add/$', StudentCreate.as_view(), name='student_add'),
    url(r'^students/delete/(?P<pk>[\d]+)/$', StudentDelete.as_view(), name='student_delete'),
)

templates/index.html
{% extends 'navigation.html' %}
{% load i18n %}

{% block pagescript%}{% endblock %}

{% block pagestyle%}

{% endblock %}

{% block content %}
    <div class="text-center">Hello, I am a main page:)</div>
{% endblock %}

templates/login.html
{% extends 'navigation.html'%}
{% load i18n %}
{% load bootstrap %}

{% block pagescript%}
{% endblock %}

{% block pagestyle%}
{% endblock %}

{% block content %}
    <div class="col-md-4 col-md-offset-4">
        <form method="post"> {% csrf_token %}
            {{ form|bootstrap }}
            <input type="submit" class="btn btn-primary" value="{% trans "Login" %}">
        </form>
    </div>
{% endblock %}

templates/main.html
{# Main template #}
{% load i18n %}
{% load static %}

<!doctype html>
<html>
<head>
    <title>{% trans 'Codeon test' %}</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    {% block basescript %} {% endblock %}
    {% block basestyle %} {% endblock %}

</head>
<body>
    <div class="container-fluid">
        <div class="row">
            {% block main_content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

templates/navigation.html
{# Navigation #}
{% extends 'main.html' %}
{% load i18n %}
{% load code_on %}

{% block basescript %}
    {% block pagescript%}
    {% endblock %}
{% endblock %}

{% block basestyle %}
    {% block pagestyle%}
    {% endblock %}
{% endblock %}

{% block main_content%}

    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
        <nav class="navbar navbar-inverse nanbar-static-top" role="navigation">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-for-collapse">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                     </button>
                     <a class="navbar-brand" href="{% url 'home' %}">{% trans 'Codeon' %}</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-for-collapse">

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'student:group_list' %}">{%  trans "Students" %}</a></li>
                            <li><a href="{% edit_url user %}">{{ user.username }}</a></li>
                            <li><a href="{% url 'logout' %}">{%  trans "Log out" %}</a></li>
                        {% else %}
                            <li><a href="{% url 'registration' %}">{% trans 'Registration' %}</a></li>
                            <li><a href="{% url 'login' %}">{% trans 'Login' %}</a></li>
                        {% endif %}
                    </ul>
                </div>
             </div>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

templates/registration.html
{% extends 'navigation.html'%}
{% load i18n %}
{% load bootstrap %}


{% block pagescript%}
{% endblock %}

{% block pagestyle%}
{% endblock %}

{% block content %}
    <div class="col-md-4 col-md-offset-4">
            <form method="post"> {% csrf_token %}
            {{ form|bootstrap }}
            <input type="submit" class="btn btn-primary" value="{% trans "Registration" %}">
        </form>
    </div>
{% endblock %}